http:
  routers:
    api:
      entrypoints:
        - websecure
      service: api@internal
  services:
    errorService:
      loadbalancer:
        server:
          port: 8080
  middlewares:
    errorpage:
      errors:
        status:
          - "400-550"
        service: quarkusservice@docker
        query: "/api/error/{status}"

tls:
  certificates:
    - certFile: ./domain.crt
      keyFile: ./domain.key
