http:
  routers:
    api:
      entrypoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
    employer:
      rule: Host(`breadcrumb.employer.com`)
      entrypoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: employerservice
    apicore:
      entrypoints:
        - websecure
      rule: "Host(`$PWA_HOST`) && Path(`/api`)"
      tls:
        certResolver: letsencrypt
  services:
    employerservice:
      loadbalancer:
        server:
          port: 3001
