entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
  dev:
    address: ':5001'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
    network: traefik-global-proxy
  file:
    filename: ./traefik_dynamic.yaml
    directory: .
